import "./globals.css";

// Import components
import { Background } from "../components/background";
import ClientLayout from "../components/ClientLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Background />
        <ClientLayout />
      </body>
    </html>
  );
}
