import "./globals.css";

import { Background } from "../components/background";
import { Hero } from "../components/hero";
import { Nav } from "../components/nav";
import { About } from "../components/about";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Background />
        <Nav />
        <Hero />
        {/* <About /> */}
      </body>
    </html>
  );
}
